apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  host: mysql-db-endpoints.datasources
  username: root
  password: 5bc1bHOiQQlg2cqVfrovVUQj
---
apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
  name: access-mysql
spec:
  desc: Allow access to MySQL
  env:
  - name: MYSQL_HOST
    valueFrom:
      secretKeyRef:
        name: mysql-secret
        key: host
        optional: false
  - name: MYSQL_USER
    valueFrom:
      secretKeyRef:
        name: mysql-secret
        key: username
        optional: false
  - name: MYSQL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mysql-secret
        key: password
        optional: false
  selector:
    matchLabels:
      access-mysql: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-secret
type: Opaque
stringData:
  host: opensearch-cluster-master.vectorstore
  port: "9200"
  username: admin
  password: admin
---
apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
  name: access-opensearch
spec:
  desc: Allow access to Opensearch
  env:
  - name: OPENSEARCH_HOST
    valueFrom:
      secretKeyRef:
        name: opensearch-secret
        key: host
        optional: false
  - name: OPENSEARCH_PORT
    valueFrom:
      secretKeyRef:
        name: opensearch-secret
        key: port
        optional: false
  - name: OPENSEARCH_USER
    valueFrom:
      secretKeyRef:
        name: opensearch-secret
        key: username
        optional: false
  - name: OPENSEARCH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: opensearch-secret
        key: password
        optional: false
  selector:
    matchLabels:
      access-opensearch: "true"
